/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.EspaceDeTraitement;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

import controler.DemandeManager;
import controler.EnvoyerEmail;
import model.Demande;
import controler.TelechargerDocument;
import controler.EnvoyerDocument;
import view.*;
/**
 *
 * @author cli
 */
public class DemandeGUI extends javax.swing.JPanel {
    private javax.swing.JButton apercuButton;
    private javax.swing.JButton accepterButton;
    private javax.swing.JButton refuserButton;
    private javax.swing.JLabel idDemande;
    private javax.swing.JLabel dateDemande;
    private javax.swing.JLabel nomEtudiant;
    private model.Demande demande;
    DemandeManager demandeManager;
    MainFrame mainFrame;

    /**
     * Creates new form Tache
     */
    public DemandeGUI(model.Demande demande, DemandeManager demandeManager) {
        this.demandeManager = demandeManager;
        this.demande = demande;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idDemande = new javax.swing.JLabel();
        dateDemande = new javax.swing.JLabel();
        nomEtudiant = new javax.swing.JLabel();
        apercuButton = new javax.swing.JButton();
        accepterButton = new javax.swing.JButton();
        refuserButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(591, 37));

        idDemande.setText(""+demande.getIdDemande());

        dateDemande.setText(demande.getDate());

        nomEtudiant.setText(demande.getNomEtudiant()+" "+demande.getPrenomEtudiant());

        apercuButton.setForeground(new java.awt.Color(51, 51, 255));
        apercuButton.setText("Aperçu");
        apercuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuButtonActionPerformed(evt);
            }
        });

        accepterButton.setForeground(new java.awt.Color(0, 204, 0));
        accepterButton.setText("Accepter");
        accepterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepterButtonActionPerformed(evt);
            }
        });

        refuserButton.setForeground(new java.awt.Color(255, 51, 51));
        refuserButton.setText("Refuser");
        refuserButton.setMaximumSize(new java.awt.Dimension(90, 23));
        refuserButton.setMinimumSize(new java.awt.Dimension(90, 23));
        refuserButton.setPreferredSize(new java.awt.Dimension(90, 23));
        refuserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(idDemande, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(dateDemande, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(nomEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(apercuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accepterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refuserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(idDemande)
                            .addComponent(dateDemande)
                            .addComponent(nomEtudiant)
                            .addComponent(apercuButton)
                            .addComponent(accepterButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(refuserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refuserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        RefuserJDialog RefuserJDialog = new RefuserJDialog(mainFrame, demande);
        RefuserJDialog.setVisible(true);
        demandeManager.refuserDemande(demande);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void accepterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AccepterJDialog accepterJDialog = new AccepterJDialog(mainFrame, demande);
        accepterJDialog.setVisible(true);
        demandeManager.accepterDemande(demande);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void apercuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(demande.getType().equals("Stage")){
            new ApercuStage(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("Attestation de réussite")){
            new ApercuReuss(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("certificat de scolarité")){
            new Apercuscola(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("Relevés de Notes")){
            new ApercuNote (demande.getIdDemande()).setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed
}

/**
 * AccepterJDialog
 */

// class AccepterJDialog extends JDialog {

//     public AccepterJDialog(JFrame parent, Demande demande) {
//         super(parent, "Document Sent", true);
//         setSize(300, 150);

//         JLabel messageLabel = new JLabel("Votre document a été envoyé.");
//         JButton downloadButton = new JButton("Télécharger");
//         JButton doNothingButton = new JButton("OK");

//         // Layout manager for better organization
//         GroupLayout layout = new GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setAutoCreateGaps(true);
//         layout.setAutoCreateContainerGaps(true);

//         // Horizontal layout
//         layout.setHorizontalGroup(layout.createSequentialGroup()
//                 .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                         .addComponent(messageLabel)
//                         .addGroup(layout.createSequentialGroup()
//                                 .addComponent(downloadButton)
//                                 .addComponent(doNothingButton)))
//         );

//         // Vertical layout
//         layout.setVerticalGroup(layout.createSequentialGroup()
//                 .addComponent(messageLabel)
//                 .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                         .addComponent(downloadButton)
//                         .addComponent(doNothingButton))
//         );

//         setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//         setLocationRelativeTo(parent);

//         // Add action listeners for the buttons
//         downloadButton.addActionListener((java.awt.event.ActionEvent e) -> {
//             // TODO: Add download functionality
//             System.out.println("Le document est téléchargé");
//         });

//         doNothingButton.addActionListener((java.awt.event.ActionEvent e) -> {
//             // Close the dialog
//             dispose();
//         });
//     }
// }
class AccepterJDialog extends JDialog {

    public AccepterJDialog(JFrame parent, Demande demande) {
        super(parent, "Document Sent", true);
        setSize(300, 120);
        setResizable(false);
        new EnvoyerDocument(demande);
        JLabel messageLabel = new JLabel("Votre document a été envoyé.");
        JButton downloadButton = new JButton("Télécharger");
        JButton doNothingButton = new JButton("OK");

        // Use FlowLayout with vertical alignment
        setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // Add components to the dialog
        add(messageLabel);
        add(downloadButton);
        add(doNothingButton);

        // Add action listeners for the buttons
        downloadButton.addActionListener((ActionEvent e) -> {
            // TODO: Add download functionality
            new TelechargerDocument(demande);
            // System.out.println("Le document est téléchargé");
        });

        doNothingButton.addActionListener((ActionEvent e) -> {
            // Close the dialog
            dispose();
        });

        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(parent);
    }
}


class RefuserJDialog extends JDialog {

    private JTextArea raisonArea;


    public RefuserJDialog(JFrame parent, Demande demande) {
        super(parent, "Refuser Document", true);
        setSize(300, 200);

        JLabel messageLabel = new JLabel("Veuillez fournir la raison du refus:");
        raisonArea = new JTextArea(5, 20);  
        JButton sendReasonButton = new JButton("Envoyer Raison");

        // Use FlowLayout with vertical alignment
        setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // Add components to the dialog
        add(messageLabel);
        add(raisonArea);
        add(sendReasonButton);
      

        // Add action listeners for the buttons
        sendReasonButton.addActionListener((ActionEvent e) -> {
            // Get the entered reason
            String reason = raisonArea.getText();
            // Print the reason to the console (you can replace this with your actual logic)
            System.out.println("Raison de refus : " + reason);
            new EnvoyerEmail(demande, reason);
            // Close the dialog
            dispose();
        });

        
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(parent);
    }
    
}

