// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package view.EspaceDeHistorique;


// /**
//  *
//  * @author cli
//  */
// public class ElementGUI extends javax.swing.JPanel {

//     /**
//      * Creates new form Tache
//      */
//     public ElementGUI() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         jLabel9 = new javax.swing.JLabel();
//         jButton4 = new javax.swing.JButton();
//         jButton7 = new javax.swing.JButton();
//         jButton8 = new javax.swing.JButton();

//         setBackground(new java.awt.Color(255, 255, 255));
//         setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//         setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
//         setMaximumSize(new java.awt.Dimension(591, 37));

//         jLabel6.setText("01");

//         jLabel7.setText("01/12/23");

//         jLabel9.setText("Nom etudiant");

//         jButton4.setForeground(new java.awt.Color(51, 51, 255));
//         jButton4.setText("Aperçu");

//         jButton7.setForeground(new java.awt.Color(0, 204, 0));
//         jButton7.setText("Renvoyer");

//         jButton8.setForeground(new java.awt.Color(255, 153, 51));
//         jButton8.setText("Télécharger");
//         jButton8.setMaximumSize(new java.awt.Dimension(90, 23));
//         jButton8.setMinimumSize(new java.awt.Dimension(90, 23));
//         jButton8.setPreferredSize(new java.awt.Dimension(90, 23));
//         jButton8.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton8ActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(22, 22, 22)
//                 .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(60, 60, 60)
//                 .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(64, 64, 64)
//                 .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(108, 108, 108)
//                 .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
//                 .addContainerGap())
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
//                             .addComponent(jLabel6)
//                             .addComponent(jLabel7)
//                             .addComponent(jLabel9)
//                             .addComponent(jButton4)
//                             .addComponent(jButton7))
//                         .addGap(0, 0, Short.MAX_VALUE))
//                     .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                 .addContainerGap())
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton8ActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton jButton4;
//     private javax.swing.JButton jButton7;
//     private javax.swing.JButton jButton8;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JLabel jLabel9;
//     // End of variables declaration//GEN-END:variables
// }
