/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.EspaceDeHistorique;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

import controler.HistoriqueManager;
import controler.TelechargerDocument;
import model.Demande;
import view.ApercuNote;
import view.ApercuReuss;
import view.ApercuStage;
import view.Apercuscola;
import view.MainFrame;
import controler.EnvoyerDocument;
/**
 *
 * @author cli
 */
public class ElementGUI extends javax.swing.JPanel {
    private javax.swing.JButton apercuButton;
    private javax.swing.JButton renvoyerButton;
    private javax.swing.JButton telechargerButton;
    private javax.swing.JLabel idDemande;
    private javax.swing.JLabel dateDemande;
    private javax.swing.JLabel nomEtudiant;
    private model.Demande demande;
    HistoriqueManager historiqueManager;
    MainFrame mainFrame;

    /**
     * Creates new form Tache
     */
    public ElementGUI(model.Demande demande, HistoriqueManager historiqueManager) {
        this.historiqueManager = historiqueManager;
        this.demande = demande;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idDemande = new javax.swing.JLabel();
        dateDemande = new javax.swing.JLabel();
        nomEtudiant = new javax.swing.JLabel();
        apercuButton = new javax.swing.JButton();
        renvoyerButton = new javax.swing.JButton();
        telechargerButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(591, 37));

        idDemande.setText(""+demande.getIdDemande());

        dateDemande.setText(demande.getDate());

        nomEtudiant.setText(demande.getNomEtudiant()+" "+demande.getPrenomEtudiant());

        apercuButton.setForeground(new java.awt.Color(51, 51, 255));
        apercuButton.setText("Aperçu");
        apercuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuButtonActionPerformed(evt);
            }
        });

        renvoyerButton.setForeground(new java.awt.Color(0, 204, 0));
        renvoyerButton.setText("Renvoyer");
        renvoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renvoyerButtonActionPerformed(evt);
            }
        });

        telechargerButton.setForeground(new java.awt.Color(255, 51, 51));
        telechargerButton.setText("Telecharger");
        telechargerButton.setMaximumSize(new java.awt.Dimension(90, 23));
        telechargerButton.setMinimumSize(new java.awt.Dimension(90, 23));
        telechargerButton.setPreferredSize(new java.awt.Dimension(90, 23));
        telechargerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telechargerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(idDemande, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(dateDemande, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(nomEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(apercuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renvoyerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telechargerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(idDemande)
                            .addComponent(dateDemande)
                            .addComponent(nomEtudiant)
                            .addComponent(apercuButton)
                            .addComponent(renvoyerButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(telechargerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void telechargerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new TelechargerDocument(demande);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void renvoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RenvoyerJDialog RenvoyerJDialog = new RenvoyerJDialog(mainFrame, demande);
        RenvoyerJDialog.setVisible(true);
        historiqueManager.RenvoyerHistorique(demande);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void apercuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(demande.getType().equals("Stage")){
            new ApercuStage(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("Attestation de réussite")){
            new ApercuReuss(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("certificat de scolarité")){
            new Apercuscola(demande.getIdDemande()).setVisible(true);
        }
        else if (demande.getType().equals("Relevés de Notes")){
            new ApercuNote (demande.getIdDemande()).setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed
}

/**
 * RenvoyerJDialog
 */

class RenvoyerJDialog extends JDialog{
    
    public RenvoyerJDialog(JFrame parent, Demande demande) {
        super(parent, "Document Sent", true);
        setSize(300, 150);
        new EnvoyerDocument(demande);
        JLabel messageLabel = new JLabel("Votre document a été envoyé.");
        JButton doNothingButton = new JButton("ok");


        // Layout manager for better organization
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        // Horizontal layout
        layout.setHorizontalGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(messageLabel)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(doNothingButton)))
        );

        // Vertical layout
        layout.setVerticalGroup(layout.createSequentialGroup()
                .addComponent(messageLabel)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(doNothingButton))
        );
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(parent);

        doNothingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });
    }
    
}



class ApercuJDialog extends JDialog{

}