// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package view.TableauDeBord;

// import java.awt.Color;
// import java.awt.Frame;

// import javax.swing.JButton;
// import javax.swing.SwingConstants;

// import model.Statistics;

// /**
//  *
//  * @author cli
//  */
// public class TableauDeBord extends javax.swing.JPanel {

//     /**
//      * Creates new form TableauDeBord
//      */
//     public TableauDeBord(view.MainFrame mainFrame) {
//         this.mainFrame = mainFrame;
//         initComponents();
//         update();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jButton1 = new javax.swing.JLabel();
//         jButton2 = new javax.swing.JLabel();
//         jButton3 = new javax.swing.JLabel();
//         jButton4 = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         zoneStatistiques = new javax.swing.JTextArea();
//         diagrammeCirculaire = new view.TableauDeBord.DiagrammeCirculaire();

//         jButton1.setText("Certificat de scolarité - ");
//         jButton1.setBackground(Color.white);
//         jButton1. setOpaque(true);
//         jButton1.setHorizontalAlignment(SwingConstants.CENTER);


//         jButton2.setText("Relevés de Notes  -");
//         jButton2.setBackground(Color.white);
//         jButton2. setOpaque(true);
//         jButton2.setHorizontalAlignment(SwingConstants.CENTER);

//         jButton3.setText("Attestation de réussite  -");
//         jButton3.setBackground(Color.white);
//         jButton3. setOpaque(true);
//         jButton3.setHorizontalAlignment(SwingConstants.CENTER);

//         jButton4.setText("Convention de stage -");
//         jButton4.setBackground(Color.white);
//         jButton4. setOpaque(true);
//         jButton4.setHorizontalAlignment(SwingConstants.CENTER);

//         jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

//         zoneStatistiques.setEditable(false);
//         zoneStatistiques.setBackground(new java.awt.Color(255, 255, 255));
//         zoneStatistiques.setColumns(20);
//         zoneStatistiques.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//         zoneStatistiques.setRows(5);
//         zoneStatistiques.setText(texteStatistiques);
//         zoneStatistiques.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
//         jScrollPane1.setViewportView(zoneStatistiques);

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//             .addGroup(layout.createSequentialGroup()
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(diagrammeCirculaire, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(12, 12, 12)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jScrollPane1)
//                     .addComponent(diagrammeCirculaire, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)))
//         );
//     }// </editor-fold>//GEN-END:initComponents


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private Statistics stat;
//     private view.TableauDeBord.DiagrammeCirculaire diagrammeCirculaire;
//     private javax.swing.JLabel jButton1;
//     private javax.swing.JLabel jButton2;
//     private javax.swing.JLabel jButton3;
//     private javax.swing.JLabel jButton4;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JTextArea zoneStatistiques;
//     private String texteStatistiques;
//     private view.MainFrame mainFrame;
//     // End of variables declaration//GEN-END:variables
//     private void mettreAJourStatistiques() {
//         // Vous pouvez remplacer le texte ci-dessous par les demandes réelles que vous souhaitez afficher 
//         jButton1.setText("Certificat de scolarité "+stat.getNum_scola());
//         jButton2.setText("Relevés de Notes  "+stat.getNum_notes());
//         jButton3.setText("Attestation de réussite  "+stat.getNum_reuss());
//         jButton4.setText("Convention de stage "+stat.getNum_stage());

//         // Vous pouvez remplacer le texte ci-dessous par les statistiques réelles que vous souhaitez afficher
//         String texteStatistiques =  "\n   • Nombre total de demandes: "+stat.getNum_dem() +"\n\n"+
//                                     "   • Demandes en attente: "+stat.getNumb_dem_att()+"\n\n"+
//                                     "   • Demandes validées: "+ stat.getNumb_val()+"\n\n"+
//                                     "   • Demandes refusées: "+stat.getNumb_ref()+"\n\n"+
//                                     "   • Nombre réclamation: "+stat.getNum_recla();

//         // Mettre à jour le texte de JTextArea
//         zoneStatistiques.setText(texteStatistiques);
//     }

//     private void mettreAJourDiagrammeCirculaire() {
//         // Mettre à jour le dataset du diagramme circulaire avec de nouvelles valeurs
//         diagrammeCirculaire.mettreAJourDonnees("Refusées", stat.getNumb_ref());
//         diagrammeCirculaire.mettreAJourDonnees("Non traitées", stat.getNumb_dem_att());
//         diagrammeCirculaire.mettreAJourDonnees("Acceptées", stat.getNumb_val());
//     }

//     public void update() {
//         System.out.println("tableau de bord is updating");
//         stat=new Statistics();
//         mettreAJourStatistiques();
//         mettreAJourDiagrammeCirculaire();
//     }


// }
