/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import view.TableauDeBord.TableauDeBord;
import view.EspaceDeTraitement.EspaceDeTraitement;
import view.EspaceDeHistorique.EspaceDeHistorique;
import view.EspaceDeReclamation.EspaceDeReclamation;

import controler.*;

/**
 *
 * @author cli
 */
public class MainFrame extends javax.swing.JFrame {
        // Variables declaration - do not modify//GEN-BEGIN:variables
    
    private String username= "NOM D'UTILISATEUR";

    private javax.swing.JButton tableauDeBordButton;
    private javax.swing.JButton EspaceDeTraitementButton;
    private javax.swing.JButton EspaceDeHistoriqueButton;
    private javax.swing.JButton EspaceDeReclamationButton;

    private TableauDeBord tableauDeBord;
    private EspaceDeTraitement espaceDeTraitement;
    private EspaceDeHistorique espaceDeHistorique;
    private EspaceDeReclamation espaceDeReclamation;

    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public void setUsername(String username) {
        jLabel10.setText(username.toUpperCase().replace(".", " "));
    }

    /**
     * Creates new form CompleteFrame
     */
    public MainFrame(TableauDeBord tableauDeBord, EspaceDeTraitement espaceDeTraitement, EspaceDeHistorique espaceDeHistorique, EspaceDeReclamation espaceDeReclamation)  {
        
        this.tableauDeBord = tableauDeBord;
        this.espaceDeTraitement = espaceDeTraitement;
        this.espaceDeHistorique = espaceDeHistorique;
        this.espaceDeReclamation = espaceDeReclamation;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tableauDeBordButton = new javax.swing.JButton();
        tableauDeBordButton.setFocusable(false);
        EspaceDeTraitementButton = new javax.swing.JButton();
        EspaceDeTraitementButton.setFocusable(false);
        EspaceDeHistoriqueButton = new javax.swing.JButton();
        EspaceDeHistoriqueButton.setFocusable(false);
        EspaceDeReclamationButton = new javax.swing.JButton();
        EspaceDeReclamationButton.setFocusable(false);
        mainPanel = new javax.swing.JPanel();
        // tableauDeBord = new view.TableauDeBord.TableauDeBord();
        // espaceDeTraitement = new view.EspaceDeTraitement.EspaceDeTraitement();
        // espaceDeHistorique = new view.EspaceDeHistorique.EspaceDeHistorique();
        // espaceDeReclamation = new view.EspaceDeReclamation.EspaceDeReclamation();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_ensate.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText(username);

        jButton9.setText("se deconnecter  ");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 649, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(34, 34, 34)))
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton9))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableauDeBordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TableauDeBordIcon.png"))); // NOI18N
        tableauDeBordButton.setText("Tableau de bord");
        tableauDeBordButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tableauDeBordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableauDeBordButtonActionPerformed(evt);
            }
        });

        EspaceDeTraitementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EspaceDeTraitementIcon.png"))); // NOI18N
        EspaceDeTraitementButton.setText("Espace de traitement");
        EspaceDeTraitementButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EspaceDeTraitementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaceDeTraitementButtonActionPerformed(evt);
            }
        });

        EspaceDeHistoriqueButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HistoriqueIcon.png"))); // NOI18N
        EspaceDeHistoriqueButton.setText("Historique");
        EspaceDeHistoriqueButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EspaceDeHistoriqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaceDeHistoriqueButtonActionPerformed(evt);
            }
        });

        EspaceDeReclamationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ReclamationIcon.png"))); // NOI18N
        EspaceDeReclamationButton.setText("Reclamation");
        EspaceDeReclamationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EspaceDeReclamationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaceDeReclamationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EspaceDeTraitementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableauDeBordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EspaceDeHistoriqueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EspaceDeReclamationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tableauDeBordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspaceDeTraitementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspaceDeHistoriqueButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspaceDeReclamationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(tableauDeBord, "Tableau de bord");
        mainPanel.add(espaceDeTraitement, "Espace de traitement");
        mainPanel.add(espaceDeHistorique, "Historique");
        mainPanel.add(espaceDeReclamation, "Reclamation");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspaceDeReclamationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaceDeReclamationButtonActionPerformed
        // TODO add your handling code here:
            JButton sourceButton = (JButton) evt.getSource();
            String buttonText = sourceButton.getText();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, buttonText);
            System.out.println(buttonText);

    }//GEN-LAST:event_EspaceDeReclamationButtonActionPerformed

    private void tableauDeBordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableauDeBordButtonActionPerformed
        // TODO add your handling code here:
            JButton sourceButton = (JButton) evt.getSource();
            String buttonText = sourceButton.getText();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            //update tableau de bord
            tableauDeBord.update();
            cardLayout.show(mainPanel, buttonText);
            System.out.println(buttonText);

    }//GEN-LAST:event_tableauDeBordButtonActionPerformed

    private void EspaceDeTraitementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaceDeTraitementButtonActionPerformed
        // TODO add your handling code here:
            JButton sourceButton = (JButton) evt.getSource();
            String buttonText = sourceButton.getText();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, buttonText);
            System.out.println(buttonText);

    }//GEN-LAST:event_EspaceDeTraitementButtonActionPerformed

    private void EspaceDeHistoriqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaceDeHistoriqueButtonActionPerformed
        // TODO add your handling code here:
            JButton sourceButton = (JButton) evt.getSource();
            String buttonText = sourceButton.getText();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, buttonText);
            System.out.println(buttonText);

    }//GEN-LAST:event_EspaceDeHistoriqueButtonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaceDeHistoriqueButtonActionPerformed
        // TODO add your handling code here:
            try {
                new Authentification().main(null);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            };
            this.dispose();
    }//GEN-LAST:event_EspaceDeHistoriqueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //TODO REPLACE THE MAIN METHOD!
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new MainFrame().setVisible(true);
        //     }
        // });
    // }

    
}
