/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.EspaceDeReclamation;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

import controler.EnvoyerEmail;
import controler.ReclamationManager;
import model.Reclamation;
import view.MainFrame;
/**
 *
 * @author cli
 */
public class ReclamationGUI extends javax.swing.JPanel {
    private javax.swing.JButton ApercuButton;
    private javax.swing.JButton repondreButton;
    private javax.swing.JLabel idReclamation;
    private javax.swing.JLabel dateReclamation;
    private javax.swing.JLabel nomEtudiant;
    private model.Reclamation reclamation;
    ReclamationManager ReclamationManager;
    MainFrame mainFrame;

    /**
     * Creates new form Tache
     */
    public ReclamationGUI(model.Reclamation Reclamation, ReclamationManager ReclamationManager) {
        this.ReclamationManager = ReclamationManager;
        this.reclamation = Reclamation;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idReclamation = new javax.swing.JLabel();
        dateReclamation = new javax.swing.JLabel();
        nomEtudiant = new javax.swing.JLabel();
        ApercuButton = new javax.swing.JButton();
        repondreButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(591, 37));

        idReclamation.setText(""+reclamation.getIdReclamation());

        dateReclamation.setText(reclamation.getDate());

        nomEtudiant.setText(reclamation.getNomEtudiant()+" "+reclamation.getPrenomEtudiant());

        

        ApercuButton.setForeground(new java.awt.Color(0, 204, 0));
        ApercuButton.setText("Apercu");
        ApercuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuButtonActionPerformed(evt);
            }
        });

        repondreButton.setForeground(new java.awt.Color(255, 51, 51));
        repondreButton.setText("repondre");
        repondreButton.setMaximumSize(new java.awt.Dimension(90, 23));
        repondreButton.setMinimumSize(new java.awt.Dimension(90, 23));
        repondreButton.setPreferredSize(new java.awt.Dimension(90, 23));
        repondreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repondreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(idReclamation, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(dateReclamation, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(nomEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ApercuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repondreButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(idReclamation)
                            .addComponent(dateReclamation)
                            .addComponent(nomEtudiant)
                            .addComponent(ApercuButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(repondreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void repondreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new RepondreJDialog(mainFrame, reclamation).setVisible(true);
        System.out.println("Repondre a la reclamation");        
    }//GEN-LAST:event_jButton8ActionPerformed

    

    private void apercuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new ApercuJDialog(reclamation).setVisible(true);;
        System.out.println("Apercu la reclamation");
    }//GEN-LAST:event_jButton7ActionPerformed
}

/**
 * ApercuJDialog
 */




class ApercuJDialog extends JDialog {

    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JScrollPane jScrollPane2;
    private JTextArea jTextArea1;

    private Reclamation reclamation;

    public ApercuJDialog(Reclamation reclamation) {
        this.reclamation = reclamation;
        initComponents();
    }

    private void initComponents() {
        jButton1 = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jTextArea1 = new JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        jButton1.setBackground(new Color(255, 255, 153));
        jButton1.setText("OK");
        jButton1.setBorder(BorderFactory.createEtchedBorder());
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jLabel1.setFont(new Font("Verdana", 1, 12));
        jLabel1.setText("Aperçu de reclamation");

        jLabel3.setFont(new Font("Segoe UI Light", 1, 14));
        jLabel3.setText("Date : " + reclamation.getDate());

        jLabel2.setFont(new Font("Segoe UI Light", 1, 14));
        jLabel2.setText("Etudiant : " + reclamation.getNomEtudiant() + " " + reclamation.getPrenomEtudiant());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
        jTextArea1.setEditable(false);
        jTextArea1.setText(reclamation.getmessageReclamation());
        jScrollPane2.setViewportView(jTextArea1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

}



class RepondreJDialog extends JDialog {

    private JTextArea raisonArea;


    public RepondreJDialog(JFrame parent, Reclamation Reclamation) {
        super(parent, "Repondre au reclamation", true);
        setSize(300, 200);

        JLabel messageLabel = new JLabel("Veuillez repondre a la reclamation:");
        raisonArea = new JTextArea(5, 20);  
        JButton sendReasonButton = new JButton("Envoyer réponse");

        // Use FlowLayout with vertical alignment
        setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        // Add components to the dialog
        add(messageLabel);
        add(raisonArea);
        add(sendReasonButton);
      

        // Add action listeners for the buttons
        sendReasonButton.addActionListener((ActionEvent e) -> {
            // Get the entered reason
            String reponse = raisonArea.getText();
            // Print the reason to the console (you can replace this with your actual logic)
            System.out.println("La réponse : " + reponse);
            new EnvoyerEmail(Reclamation, reponse);
            // Close the dialog
            dispose();
        });

        
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(parent);
    }
    
}

